/**
 * PHASE 3 — Generated-papers management (real /api/v3/papers).
 *
 * Filters School / Teacher scope / Course / Class / Subject / Status /
 * Date / search — all executed server-side with strict school isolation
 * (a school admin only ever sees their own school's papers).
 */
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import {
  Copy, Download, ExternalLink, FileStack, Loader2, Search, Trash2,
} from 'lucide-react';
import { useAppSelector } from '../../store/hooks';
import { v3 } from '../../api/v3';
import { EmptyState, PageHeader, StatusBadge } from '../../components/ui';
import type { PaperRowV3 } from '../../types';

export default function AdminPapersPage() {
  const { user: me } = useAppSelector((s) => s.auth);
  const isSuper = me?.role === 'super_admin';
  const [rows, setRows] = useState<PaperRowV3[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [busyId, setBusyId] = useState<number | null>(null);
  const [f, setF] = useState({
    status: '', search: '', schoolId: '', from: '', to: '', subjectId: '', classId: '',
  });

  const fetchRows = useCallback(async () => {
    try {
      const res = await v3.papers.list({
        page, limit: 15,
        status: f.status || undefined,
        search: f.search || undefined,
        schoolId: f.schoolId ? Number(f.schoolId) : undefined,
        from: f.from || undefined,
        to: f.to || undefined,
        subjectId: f.subjectId ? Number(f.subjectId) : undefined,
        classId: f.classId ? Number(f.classId) : undefined,
      });
      setRows(res.data.data.rows);
      setTotal(res.data.data.total);
    } catch (e: any) {
      toast.error(e?.response?.data?.message || 'Failed to load papers');
    }
  }, [page, f]);

  useEffect(() => { fetchRows(); }, [fetchRows]);

  const run = async (id: number, fn: () => Promise<unknown>, ok: string) => {
    setBusyId(id);
    try { await fn(); toast.success(ok); fetchRows(); }
    catch (e: any) { toast.error(e?.response?.data?.message || 'Action failed'); }
    finally { setBusyId(null); }
  };

  const downloadPdf = async (p: PaperRowV3) => {
    setBusyId(p.id);
    const res = await v3.papers.downloadPdf(p.id);
    if (!res.ok) toast.error(res.message || 'PDF download failed');
    else toast.success('PDF downloaded (with branding)');
    setBusyId(null);
  };

  const setStatus = (p: PaperRowV3, status: string) => run(p.id, () => v3.papers.setStatus(p.id, status), `Paper → ${status}`);

  const pages = Math.max(1, Math.ceil(total / 15));
  const set = (k: keyof typeof f, v: string) => { setF((x) => ({ ...x, [k]: v })); setPage(1); };

  return (
    <div className="max-w-7xl mx-auto px-4 py-6">
      <PageHeader title="Papers (All)" description={`${total} papers across scope · strict school isolation is enforced server-side`} />

      <div className="card p-3 mb-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-2">
        <div className="relative">
          <Search className="w-4 h-4 text-surface-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input className="input pl-9" placeholder="Search title…" value={f.search} onChange={(e) => set('search', e.target.value)} />
        </div>
        <select className="select" value={f.status} onChange={(e) => set('status', e.target.value)}>
          <option value="">All statuses</option>
          {['draft', 'final', 'archived'].map((s) => <option key={s} value={s}>{s}</option>)}
        </select>
        {isSuper ? (
          <SchoolFilter value={f.schoolId} onChange={(v) => set('schoolId', v)} />
        ) : (
          <div className="input text-surface-500 truncate">{me?.schoolName ?? 'My school'}</div>
        )}
        <div className="grid grid-cols-2 gap-2">
          <input type="date" className="input" value={f.from} title="From" onChange={(e) => set('from', e.target.value)} />
          <input type="date" className="input" value={f.to} title="To" onChange={(e) => set('to', e.target.value)} />
        </div>
      </div>

      {rows.length === 0 && page === 1 ? (
        <EmptyState icon={FileStack} title="No papers found" description="Papers generated by teachers appear here once they are created." />
      ) : (
        <>
          <div className="card overflow-x-auto">
            <table className="w-full text-sm min-w-195">
              <thead>
                <tr className="text-left text-[10.5px] uppercase tracking-wider text-surface-400 border-b border-surface-200">
                  <th className="px-4 py-2.5">Paper</th>
                  <th className="px-4 py-2.5">School / Teacher</th>
                  <th className="px-4 py-2.5">Class · Subject</th>
                  <th className="px-4 py-2.5 text-right">Marks</th>
                  <th className="px-4 py-2.5">Status</th>
                  <th className="px-4 py-2.5 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-100">
                {rows.map((p) => (
                  <tr key={p.id} className="hover:bg-surface-50/70 transition-colors">
                    <td className="px-4 py-3 min-w-56">
                      <Link to={`/app/papers/${p.id}`} className="block text-surface-900 font-semibold hover:text-brand-700 truncate max-w-64">
                        {p.title} <ExternalLink className="w-3 h-3 inline text-surface-300" />
                      </Link>
                      <span className="text-[10.5px] text-surface-400">#{p.id} · {p.medium} · {new Date(p.createdAt).toLocaleDateString()}</span>
                    </td>
                    <td className="px-4 py-3 min-w-44">
                      <div className="text-xs font-medium text-surface-700">{p.teacherName}</div>
                      <div className="text-[10.5px] text-surface-400">{p.schoolId ? `School #${p.schoolId}` : '—'}</div>
                    </td>
                    <td className="px-4 py-3 min-w-40">
                      <div className="text-xs text-surface-700">{p.className}{p.grade ? ` · Grade ${p.grade}` : ''}</div>
                      <div className="text-[10.5px] text-surface-400 truncate">{(p.subjects ?? []).map((s) => s.name).join(', ') || '—'}</div>
                    </td>
                    <td className="px-4 py-3 text-right font-bold text-surface-800">{p.totalMarks}</td>
                    <td className="px-4 py-3"><StatusBadge status={p.status} /></td>
                    <td className="px-4 py-3">
                      <div className="flex items-center justify-end gap-1">
                        {busyId === p.id && <Loader2 className="w-3.5 h-3.5 animate-spin text-surface-300" />}
                        <button className="btn-ghost btn-icon" title="Download branded PDF" onClick={() => downloadPdf(p)}><Download className="w-3.5 h-3.5" /></button>
                        <button className="btn-ghost btn-icon" title="Duplicate" onClick={() => run(p.id, () => v3.papers.duplicate(p.id), 'Duplicated as draft')}><Copy className="w-3.5 h-3.5" /></button>
                        {p.status !== 'final' && (
                          <button className="btn-ghost btn-icon text-emerald-600" title="Mark final" onClick={() => setStatus(p, 'final')}><FileStack className="w-3.5 h-3.5" /></button>
                        )}
                        {p.status !== 'archived' && (
                          <button className="btn-ghost btn-icon text-red-500" title="Archive" onClick={() => setStatus(p, 'archived')}><Trash2 className="w-3.5 h-3.5" /></button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="flex items-center justify-center gap-2 mt-4">
            <button className="btn-ghost btn-sm" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>← Prev</button>
            <span className="text-xs text-surface-500">Page {page} / {pages}</span>
            <button className="btn-ghost btn-sm" disabled={page >= pages} onClick={() => setPage((p) => p + 1)}>Next →</button>
          </div>
        </>
      )}
    </div>
  );
}

function SchoolFilter({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const [schools, setSchools] = useState<Array<{ id: number; name: string }>>([]);
  useEffect(() => { v3.schools.list({ page: 1, limit: 200 }).then((r) => setSchools(r.data.data.rows)).catch(() => undefined); }, []);
  return (
    <select className="select" value={value} onChange={(e) => onChange(e.target.value)}>
      <option value="">All schools</option>
      {schools.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
    </select>
  );
}
